### ISSUE TITLE
Browser process to 100% CPU

### ISSUE THREAD

**Issue by azman0101** [jcuga/proxyblock#1]
Chrome proc:
http://www.tiikoni.com/tis/view/?id=e3245a2

```
2015/10/31 06:15:31 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:32 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:32 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:33 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:33 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:34 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:34 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:35 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:35 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:36 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:36 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:37 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:37 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
2015/10/31 06:15:38 Handling HTTP request at  /events?timeout=15&category=http://test-orientation.studyrama.com/choixType.php&since_time=2015-10-31T06:15:02.859136665+01:00
2015/10/31 06:15:38 Error parsing last_event_time arg. Error: %!!(MISSING)s(<nil>).
```

https://gist.githubusercontent.com/azman0101/afdb7b59c6c270525a8e/raw/6ffcff71514f870becfd2a09a8d5deef1d702f6e/test-orientation.studyrama.com.har

**Comment by jcuga** [comment]
Sounds like it is trying to subscribe to the allowed/blocked URL events but the event HTTP handler is breaking on parsing the param, so the browser keeps asking again.

This means:
1) I believe my timestamp parsing is not international safe--it likely makes assumptions about how timestamps are on my machine.

2)  I need to have the client (browser) code wait longer between requests for events when the request fails.

Will try go work on this relatively soon.  Thanks for the issue submit!  Did you build the project from source, or use one of the released binaries?  (and if so, which one?)

This reminds me,  I need to run `top` on the proxyblock process itself and make sure I'm not pegging CPU either...

**Comment by jcuga** [comment]
Update:  The CPU pegging issue should be mitigated by:  0f2e3d2549927a27a01293abc97ff3a8fe9a2d20

The issue was that I had a hacky sleep() function that was just a CPU hogging loop instead of coding with a lean setTimeout().  So even though I was calling sleep before making another request, it was eating all the CPU while sleeping.

What's left is to make the timestamp related variables international safe.  So this is half fixed.

Also, I checked CPU usage for the actual proxyblock binary, and it seems nice and low.  Anyone let me know if they experience otherwise.

**Comment by jcuga** [comment]
Timestamp issue should now be addressed by 0c9930bd46b37304f820ed547efc626614cc320a

@azman0101 both problems identified by your issue should now be addressed.  I also released new binaries since these two problems were pretty serious.  Let me know if this fixes things for you and I'll close the issue.  Thanks!

**Comment by azman0101** [comment]
Thxs, I'll try soon. 

I build the project from the source

**Comment by jcuga** [comment]
@azman0101  can I close this?

**Comment by azman0101** [comment]
Sorry, I've been very busy this week. I'll try soon.
You can close it.
